! (C) Copyright 2026- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

SUBMODULE (MPL_ALLOCATOR_MOD) MPL_ALLOCATOR_SMOD
USE FIAT_BUDDY_MOD, ONLY : FIAT_BUDDY
#if HAVE_PLUTO
USE PLUTO_MODULE, ONLY : PLUTO, PLUTO_ALLOCATOR
TYPE(PLUTO_ALLOCATOR) :: MPL_PLUTO_ALLOCATOR
CHARACTER(LEN=256), SAVE :: MPL_RESOURCE_ = "mpi_pool"
#else
CHARACTER(LEN=256), SAVE :: MPL_RESOURCE_ = "BUDDY_ALLOC"
#endif
TYPE(FIAT_BUDDY) :: MPL_BUDDY_ALLOCATOR

LOGICAL, SAVE :: MPL_ALLOCATOR_INITIALIZED_ = .FALSE.
LOGICAL, SAVE :: MPL_ALLOCATOR_USED_UNINITIALIZED_ = .FALSE.
LOGICAL, SAVE :: LUSE_FORTRAN_ALLOCATE = .TRUE.
LOGICAL, SAVE :: LUSE_BUDDY_ALLOC = .FALSE.

CONTAINS

MODULE PROCEDURE MPL_ALLOCATOR_INITIALIZED
  INITIALIZED = MPL_ALLOCATOR_INITIALIZED_
END PROCEDURE

SUBROUTINE ASSERT_MPL_ALLOCATOR_INITIALIZED()
  USE MPL_MODULE, ONLY: MPL_ABORT
  IF (.NOT. MPL_ALLOCATOR_INITIALIZED_) THEN
    CALL MPL_ABORT("ERROR: MPL allocator is not initialized. Call MPL_ALLOCATOR_INIT() before using the allocator.")
  END IF
END SUBROUTINE

SUBROUTINE ABORT_RESOURCE_NOT_YET_IMPLEMENTED()
  USE MPL_MODULE, ONLY: MPL_ABORT
  CALL MPL_ABORT("ERROR: MPL resource """//TRIM(MPL_RESOURCE_)//""" is not yet implemented.")
END SUBROUTINE

SUBROUTINE ABORT_PLUTO_NOT_AVAILABLE()
  USE MPL_MODULE, ONLY: MPL_ABORT
  CALL MPL_ABORT("ERROR: FIAT was not compiled with pluto for resource """//TRIM(MPL_RESOURCE_)//"""")
END SUBROUTINE

SUBROUTINE HANDLE_UNINITIALIZED()
  MPL_ALLOCATOR_USED_UNINITIALIZED_ = .TRUE.
  IF (HAVE_PLUTO == 0) THEN
    LUSE_FORTRAN_ALLOCATE = .TRUE.
  ENDIF
END SUBROUTINE

MODULE PROCEDURE MPL_RESOURCE
  ALLOCATE(character(len=LEN_TRIM(MPL_RESOURCE_)) :: RESOURCE)
  RESOURCE = TRIM(MPL_RESOURCE_)
END PROCEDURE MPL_RESOURCE

MODULE PROCEDURE MPL_ALLOCATOR_INIT
  USE, INTRINSIC :: ISO_C_BINDING, ONLY : C_SIZE_T, C_INT64_t
  USE MPL_MODULE, ONLY : MPL_ABORT, MPL_UNIT, MPL_OUTPUT
  IMPLICIT NONE
  INTEGER(C_INT64_t) :: NRESERVE
  IF (MPL_ALLOCATOR_USED_UNINITIALIZED_) THEN
    CALL MPL_ABORT("ERROR: MPL allocator was already used before MPL_ALLOCATOR_INIT was called. &
                   &Make sure to call MPL_ALLOCATOR_INIT first.")
  ENDIF

  if (MPL_OUTPUT > 0) THEN
    IF (PRESENT(RESOURCE) .AND. PRESENT(RESERVE)) THEN
      WRITE(MPL_UNIT,'(3A,I0,A)') "+ MPL_ALLOCATOR_INIT:(RESOURCE=""",TRIM(RESOURCE),""", RESERVE=",RESERVE,")"
    ELSE IF (PRESENT(RESOURCE)) THEN
      WRITE(MPL_UNIT,'(A,I0,A)') "+ MPL_ALLOCATOR_INIT(RESOURCE=""",TRIM(RESOURCE),""")"
    ELSE IF (PRESENT(RESERVE)) THEN
      WRITE(MPL_UNIT,'(A,I0,A)') "+ MPL_ALLOCATOR_INIT(RESERVE=",RESERVE,")"
    ELSE
      WRITE(MPL_UNIT,'(A)') "+ MPL_ALLOCATOR_INIT()"
    END IF
  END IF

  NRESERVE = 0
  IF (PRESENT(RESOURCE)) THEN
    IF (LEN_TRIM(RESOURCE) /= 0) THEN
      MPL_RESOURCE_ = TRIM(RESOURCE)
    ENDIF
  ENDIF
  IF (PRESENT(RESERVE)) THEN
    NRESERVE = RESERVE
  END IF

  LUSE_FORTRAN_ALLOCATE = .FALSE.
  IF (MPL_RESOURCE_ == "FORTRAN") THEN
    LUSE_FORTRAN_ALLOCATE = .TRUE.
  ELSEIF (MPL_RESOURCE_ == "BUDDY_ALLOC") THEN
    LUSE_BUDDY_ALLOC = .TRUE.
    CALL MPL_BUDDY_ALLOCATOR%INIT(INT(NRESERVE,C_SIZE_T))
  ELSE
#if HAVE_PLUTO
    IF (.NOT. PLUTO%HAS_REGISTERED_RESOURCE(MPL_RESOURCE_)) THEN
      CALL MPL_ABORT("ERROR: MPL resource """//TRIM(MPL_RESOURCE_)//""" is not registered in pluto.")
    ENDIF
    CALL PLUTO%RESERVE(PLUTO%GET_REGISTERED_RESOURCE(MPL_RESOURCE_), NRESERVE)
    MPL_PLUTO_ALLOCATOR = PLUTO%MAKE_ALLOCATOR(MPL_RESOURCE_)
#else
    CALL ABORT_PLUTO_NOT_AVAILABLE()
#endif
  ENDIF
  IF (MPL_OUTPUT > 0) THEN
    WRITE(MPL_UNIT,'(3A)')       "MPL_ALLOCATOR_INIT : RESOURCE=""",TRIM(MPL_RESOURCE_),""""
    WRITE(MPL_UNIT,'(A,F0.2,A)') "MPL_ALLOCATOR_INIT : RESERVE=",REAL(NRESERVE/(1024**3)),"GB"
  ENDIF
  MPL_ALLOCATOR_INITIALIZED_ = .TRUE.
END PROCEDURE MPL_ALLOCATOR_INIT

MODULE PROCEDURE MPL_ALLOCATOR_FINALIZE
  USE MPL_MODULE, ONLY : MPL_UNIT, MPL_OUTPUT
  CALL ASSERT_MPL_ALLOCATOR_INITIALIZED()
  IF (MPL_OUTPUT>0) THEN
    WRITE(MPL_UNIT,'(A)') "+ MPL_ALLOCATOR_FINALIZE()"
  ENDIF
  MPL_ALLOCATOR_INITIALIZED_ = .FALSE.
  MPL_ALLOCATOR_USED_UNINITIALIZED_ = .FALSE.
  IF (LUSE_BUDDY_ALLOC) THEN
    CALL MPL_BUDDY_ALLOCATOR%FINAL()
  END IF
END PROCEDURE MPL_ALLOCATOR_FINALIZE

MODULE PROCEDURE MPL_ALLOCATE_LABEL_ARRAY_BOUNDS
  IF (.NOT. MPL_ALLOCATOR_INITIALIZED_) CALL HANDLE_UNINITIALIZED()
  IF (LUSE_FORTRAN_ALLOCATE) THEN
    ALLOCATE(ARRAY(LBOUNDS(1):UBOUNDS(1), LBOUNDS(2):UBOUNDS(2)))
  ELSE IF (LUSE_BUDDY_ALLOC) THEN
    CALL MPL_BUDDY_ALLOCATOR%ALLOCATE(ARRAY, LBOUNDS=LBOUNDS, UBOUNDS=UBOUNDS)
  ELSE
#if HAVE_PLUTO
    CALL MPL_PLUTO_ALLOCATOR%ALLOCATE(LABEL, ARRAY, LBOUNDS, UBOUNDS)
#else
    CALL ABORT_PLUTO_NOT_AVAILABLE()
#endif
  ENDIF
END PROCEDURE
MODULE PROCEDURE MPL_ALLOCATE_LABEL_ARRAY_SHAPE
  IF (.NOT. MPL_ALLOCATOR_INITIALIZED_) CALL HANDLE_UNINITIALIZED()
  IF (LUSE_FORTRAN_ALLOCATE) THEN
    ALLOCATE(ARRAY(SHAPE(1), SHAPE(2)))
  ELSE IF (LUSE_BUDDY_ALLOC) THEN
    CALL MPL_BUDDY_ALLOCATOR%ALLOCATE(ARRAY, SHAPE)
  ELSE
#if HAVE_PLUTO
    CALL MPL_PLUTO_ALLOCATOR%ALLOCATE(LABEL, ARRAY, SHAPE)
#else
    CALL ABORT_PLUTO_NOT_AVAILABLE()
#endif
  ENDIF
END PROCEDURE
MODULE PROCEDURE MPL_DEALLOCATE_LABEL_ARRAY
  IF (LUSE_FORTRAN_ALLOCATE) THEN
    DEALLOCATE(ARRAY)
  ELSE IF (LUSE_BUDDY_ALLOC) THEN
    CALL MPL_BUDDY_ALLOCATOR%DEALLOCATE(ARRAY)
  ELSE
#if HAVE_PLUTO
    CALL MPL_PLUTO_ALLOCATOR%DEALLOCATE(LABEL, ARRAY)
#else
    CALL ABORT_PLUTO_NOT_AVAILABLE()
#endif
  ENDIF
END PROCEDURE

END SUBMODULE
