MODULE FIAT_BUDDY_MOD

USE EC_PARKIND, ONLY : JPIM, JPIB, JPRM, JPRD
USE ISO_C_BINDING, ONLY : C_PTR, C_SIZE_T, C_LOC, C_F_POINTER, C_ASSOCIATED, C_NULL_PTR

IMPLICIT NONE

INTERFACE

  SUBROUTINE FIAT_BUDDY_NEW (HEAP, SIZE) BIND (C, NAME='c_fiat_buddy_new')
    IMPORT :: C_PTR, C_SIZE_T
    TYPE (C_PTR), INTENT(OUT) :: HEAP
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZE
  END SUBROUTINE

  SUBROUTINE FIAT_BUDDY_DELETE (HEAP) BIND (C, NAME='c_fiat_buddy_delete')
    IMPORT :: C_PTR
    TYPE (C_PTR), VALUE, INTENT(IN) :: HEAP
  END SUBROUTINE

  SUBROUTINE FIAT_BUDDY_ALLOCATE (HEAP, SIZE, PTR) BIND (C, NAME='c_fiat_buddy_allocate')
    IMPORT :: C_PTR, C_SIZE_T
    TYPE (C_PTR), INTENT(IN), VALUE :: HEAP
    INTEGER (C_SIZE_T), VALUE, INTENT(IN) :: SIZE
    TYPE (C_PTR), INTENT(OUT) :: PTR
  END SUBROUTINE

  SUBROUTINE FIAT_BUDDY_DEALLOCATE (HEAP, PTR) BIND (C, NAME='c_fiat_buddy_deallocate')
    IMPORT :: C_PTR
    TYPE (C_PTR), VALUE, INTENT(IN) :: HEAP
    TYPE (C_PTR), VALUE, INTENT(IN) :: PTR
  END SUBROUTINE

END INTERFACE

PRIVATE 

PUBLIC :: FIAT_BUDDY

TYPE FIAT_BUDDY
  TYPE (C_PTR) :: PTR = C_NULL_PTR
CONTAINS
  PROCEDURE :: INIT => FIAT_BUDDY_INIT
  PROCEDURE :: FINAL => FIAT_BUDDY_FINAL
  PROCEDURE, PRIVATE :: FIAT_BUDDY_ALLOCATE_ARRAY
  GENERIC :: ALLOCATE => FIAT_BUDDY_ALLOCATE_ARRAY
  PROCEDURE, PRIVATE :: FIAT_BUDDY_DEALLOCATE_ARRAY
  GENERIC :: DEALLOCATE => FIAT_BUDDY_DEALLOCATE_ARRAY
END TYPE FIAT_BUDDY

CONTAINS

SUBROUTINE FIAT_BUDDY_INIT (SELF, SIZE)

CLASS (FIAT_BUDDY) :: SELF
INTEGER (KIND=C_SIZE_T), INTENT (IN) :: SIZE

CALL FIAT_BUDDY_NEW (SELF%PTR, SIZE)

END SUBROUTINE FIAT_BUDDY_INIT

SUBROUTINE FIAT_BUDDY_FINAL (SELF)

CLASS (FIAT_BUDDY) :: SELF

CALL FIAT_BUDDY_DELETE (SELF%PTR)

SELF%PTR = C_NULL_PTR

END SUBROUTINE FIAT_BUDDY_FINAL

SUBROUTINE FIAT_BUDDY_ALLOCATE_ARRAY (SELF, P, UBOUNDS, LBOUNDS)

CLASS (FIAT_BUDDY) :: SELF
REAL(KIND=JPRD), POINTER :: P (:,:) 
INTEGER (KIND=JPIM), INTENT (IN) :: UBOUNDS (2)
INTEGER (KIND=JPIM), INTENT (IN), OPTIONAL :: LBOUNDS (2)

INTEGER (KIND=JPIM) :: ILBOUNDS (2)
TYPE (C_PTR) :: PTR
INTEGER (KIND=C_SIZE_T) :: ISIZE

ILBOUNDS = 1

IF (PRESENT (LBOUNDS)) ILBOUNDS = LBOUNDS

IF (.NOT. C_ASSOCIATED (SELF%PTR)) THEN
  ALLOCATE (P (ILBOUNDS(1):UBOUNDS(1), ILBOUNDS(2):UBOUNDS(2)))
  RETURN
ENDIF

ISIZE = INT (KIND (P), C_SIZE_T)
ISIZE = ISIZE * INT (UBOUNDS(1)-ILBOUNDS(1)+1, C_SIZE_T)
ISIZE = ISIZE * INT (UBOUNDS(2)-ILBOUNDS(2)+1, C_SIZE_T)

CALL FIAT_BUDDY_ALLOCATE (SELF%PTR, ISIZE, PTR)

CALL C_F_POINTER (PTR, P, UBOUNDS-ILBOUNDS+1)

P (ILBOUNDS(1):, ILBOUNDS(2):) => P

END SUBROUTINE FIAT_BUDDY_ALLOCATE_ARRAY

SUBROUTINE FIAT_BUDDY_DEALLOCATE_ARRAY (SELF, P)

CLASS (FIAT_BUDDY) :: SELF
REAL (KIND=JPRD), POINTER :: P(:,:) 

TYPE (C_PTR) :: PTR

IF (.NOT. ASSOCIATED (P)) THEN
  RETURN
ENDIF

IF (.NOT. C_ASSOCIATED (SELF%PTR)) THEN
  DEALLOCATE (P)
  P => NULL ()
  RETURN
ENDIF

PTR = C_LOC (P(LBOUND(P,1), LBOUND(P,2)))

CALL FIAT_BUDDY_DEALLOCATE (SELF%PTR, PTR)

P => NULL ()

END SUBROUTINE FIAT_BUDDY_DEALLOCATE_ARRAY

END MODULE FIAT_BUDDY_MOD

