macro(fiat_find_pluto)
  set(HAVE_PLUTO 0)
  if (NOT DEFINED FIAT_ENABLE_PLUTO AND NOT DEFINED ENABLE_PLUTO)
    find_package(pluto QUIET)
  elseif (DEFINED FIAT_ENABLE_PLUTO)
    if (FIAT_ENABLE_PLUTO)
      find_package(pluto)
      if (NOT pluto_FOUND)
        ecbuild_error("pluto not found, but FEATURE PLUTO is ON (FIAT_ENABLE_PLUTO=ON). Please install pluto or disable FEATURE PLUTO")
      endif()
    endif()
  elseif (DEFINED ENABLE_PLUTO)
    if (ENABLE_PLUTO)
      find_package(pluto)
      if (NOT pluto_FOUND)
        ecbuild_error("pluto not found, but FEATURE PLUTO is ON (ENABLE_PLUTO=ON). Please install pluto or disable FEATURE PLUTO")
      endif()
    endif()
  endif()
  if (pluto_FOUND)
    message(STATUS "fiat found pluto (version ${pluto_VERSION}): ${pluto_DIR})")
    message(STATUS "Feature PLUTO enabled")
    set( HAVE_PLUTO 1 )
  else()
    message(STATUS "Feature PLUTO was not enabled (also not requested) -- following packages weren't found: pluto")
  endif()
endmacro()

